# -*- coding: utf-8 -*-
"""Modified Pendant Drop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itpoglEM0UeAwXRnPs6h1bzJwINwaXWs
"""

# Read image
# Find hough lines and rotate image till it is vertical
# Do edge detection and store as colored edges
# Find the bounding box
# Calculate IFT

import cv2
import numpy as np
import imutils
import itertools
import math
import itertools

original_image = cv2.imread('a2.jpg')

image_copy = original_image.copy()
gray = cv2.cvtColor(image_copy, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray, (25, 25), 0)
edges = cv2.Canny(blurred, 30, 90)
color_edges = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)

contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for contour in contours:
    # Approximate the contour to make a polygon
    epsilon = 0.001 * cv2.arcLength(contour, True)
    approx = cv2.approxPolyDP(contour, epsilon, True)
    # Draw the contour on the original image
    cv2.drawContours(color_edges, [approx], -1, (255, 255, 255), 3)
# Display the result
# cv2_imshow( color_edges)

image_copy = original_image.copy()
lines = cv2.HoughLinesP(edges, 1, np.pi/180, threshold=100, minLineLength=100, maxLineGap=10)

selected_lines=[]
if(lines.any() and len(lines)>=2):
  for line1, line2 in itertools.combinations(lines, 2):
      x1_line1, _, x2_line1, _ = line1[0]
      x1_line2, _, x2_line2, _ = line2[0]

      # Check if the difference in x-coordinates is greater than 10 units
      if abs(x1_line1 - x1_line2) > 10 or abs(x2_line1 - x2_line2) > 10:
          print("Distinct lines found")
          selected_lines.append(line1)
          selected_lines.append(line2)
          pixel_width=abs(x1_line1-x1_line2)
          break
print(pixel_width)
# Display the lines on the image
for line in selected_lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(image_copy, (x1, y1), (x2, y2), (0, 255, 0),2)
# cv2_imshow(image_copy)

x1, y1, x2, y2 = selected_lines[1][0]
angle = np.arctan2(y2 - y1, x2 - x1) * 180.0 / np.pi
rotation_step = 1  # Adjust as needed
print("Original: ",angle)

rotated_image=image_copy.copy()
rotated_edges = color_edges.copy()

# Rotate the image until the angle becomes vertical (within a tolerance)
while abs(abs(angle)-90) >=1:  # Define a tolerance, adjust as needed
    if(abs(angle) ==90):
      break
    # Rotate the image by the defined step size
    rotated_edges_temp = imutils.rotate_bound(color_edges, rotation_step)
    rotated_img_temp = imutils.rotate_bound(image_copy, rotation_step)

    # Extract the angle of the first selected line in the rotated image
    edges_rotated = cv2.Canny(rotated_edges_temp, 30, 90)
    lines_rotated = cv2.HoughLinesP(edges_rotated, 1, np.pi / 180, threshold=100, minLineLength=100, maxLineGap=10)
    if lines_rotated is not None and len(lines_rotated) >= 2:
        x1, y1, x2, y2 = lines_rotated[0][0]
        angle = np.arctan2(y2 - y1, x2 - x1) * 180.0 / np.pi
    print(abs(angle-90))

    # Update the original image with the rotated image
    rotated_edges = rotated_edges_temp
    rotated_image=rotated_img_temp
# Display the final rotated image
# cv2_imshow(rotated_image)

# image=original_image.copy()
r_img_copy=rotated_image.copy()
gray = cv2.cvtColor(rotated_edges, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 30, 90)
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

distance=0
lowermost_point_y=-9999999
for contour in contours:
    # Find the lowermost point in the contour
    new_lowermost_point = max(contour, key=lambda point: point[0][1])
    if new_lowermost_point[0][1] > lowermost_point_y:
      lowermost_point_y=new_lowermost_point[0][1]
      lowermost_point=np.array([new_lowermost_point[0][0]+9, new_lowermost_point[0][1]])
      print("Lowermost point:", lowermost_point_y)
      selected_contour=contour

x, y, w, h = cv2.boundingRect(selected_contour)

# Draw the bounding box
cv2.rectangle(r_img_copy, (x, y), (x + w, y + h), (0, 255, 0), 2)
# touching_points = find_touching_points(contour, (x, y, w, h))
w=w
horizontal_line_y = lowermost_point[1] - w

print("Horizontal line y-coordinate:", horizontal_line_y)

# Draw the horizontal line
cv2.line(r_img_copy, (x, horizontal_line_y), (x + w, horizontal_line_y), (0, 0, 255), 2)

# Find the intersection points where the horizontal line intersects the contour
intersection_points = []
for point in selected_contour:
    px, py = point[0]
    if py == horizontal_line_y or py==horizontal_line_y +1 or py==horizontal_line_y - 1:
        intersection_points.append(point[0])

# Draw a blue circle at each intersection point
for point in intersection_points:
    cv2.circle(r_img_copy, tuple(point), 3, (255, 0, 0), -1)
# # Draw a blue circle at each touching point
# for point in touching_points:
#     cv2.circle(image, tuple(point), 5, (255, 0, 0), -1)
# Draw a blue circle at the lowermost point
if len(intersection_points) >= 2:
    for i in range(len(intersection_points) - 1):
        for j in range(i + 1, len(intersection_points)):
            point1 = intersection_points[i]
            point2 = intersection_points[j]
            newDistance=math.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)
            print(f"Distance between {point1} and {point2}: {newDistance:.2f}")
            if newDistance>distance:
              distance = math.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)


cv2.circle(r_img_copy, tuple(lowermost_point), 5, (255, 0, 0), -1)

print(f"Final Distance between {point1} and {point2}: {distance:.2f}")
# cv2.drawContours(r_img_copy, selected_contour, -1, (0,255,0), 2)
# cv2_imshow(r_img_copy)

S=distance/w
print(distance)
print(w)
scale=0.0012/pixel_width
D=w*scale
print("D:", round(D, 5), "m")
print("S: ",S)
def assign_values(S):
    if 0.401 <= S < 0.46:
        A, B4, B3, B2, B1, B0 = 2.56651, 0.3272, 0, 0.97553, 0.84059, 0.18069
    elif 0.46 <= S < 0.59:
        A, B4, B3, B2, B1, B0 = 2.59725, 0.31968, 0, 0.46898, 0.50059, 0.13261
    elif 0.59 <= S < 0.68:
        A, B4, B3, B2, B1, B0 = 2.62435, 0.31522, 0, 0.11714, 0.15756, 0.05285
    elif 0.68 <= S < 0.9:
        A, B4, B3, B2, B1, B0 = 2.64267, 0.31345, 0, 0.09155, 0.14701, 0.05877
    elif 0.9 <= S <= 1.00:
        A, B4, B3, B2, B1, B0 = 2.84636, 0.30715, 0.69116, 1.08315, 0.18341, 0.2097
    else:
        raise ValueError("S value is out of the expected range.")
        # A, B4, B3, B2, B1, B0 = 0,0,0,0,0,0
    return A, B4, B3, B2, B1, B0

A, B4, B3, B2, B1, B0 = assign_values(S)
print(f"A: {A}, B4: {B4}, B3: {B3}, B2: {B2}, B1: {B1}, B0: {B0}")

InvH= B4/(pow(S,A))+ B3*(pow(S,3))-B2*(pow(S,2))+B1*S-B0 #calculate 1/H

sigma=1000*(867-1.293)*9.81*(pow(D,2)) *InvH #1000 kg/m3 is delta rho, 9.81m/s2 is g

print("sigma: ",sigma, "mN/m")

# x, y, w, h = cv2.boundingRect(selected_contour)

# # Draw the bounding box
# cv2.rectangle(r_img_copy, (x, y), (x + w+2, y + h), (0, 255, 0), 2)
# # touching_points = find_touching_points(contour, (x, y, w, h))
# w=w+2
# horizontal_line_y = lowermost_point[1] - w

# print("Horizontal line y-coordinate:", horizontal_line_y)

# # Draw the horizontal line
# cv2.line(r_img_copy, (x, horizontal_line_y), (x + w, horizontal_line_y), (0, 0, 255), 2)

# # Find the intersection points where the horizontal line intersects the contour
# intersection_points = []
# for point in contour:
#     px, py = point[0]
#     if py == horizontal_line_y:
#         intersection_points.append(point[0])

# # Draw a blue circle at each intersection point
# for point in intersection_points:
#     cv2.circle(r_img_copy, tuple(point), 3, (255, 0, 0), -1)
# # # Draw a blue circle at each touching point
# # for point in touching_points:
# #     cv2.circle(image, tuple(point), 5, (255, 0, 0), -1)
# # Draw a blue circle at the lowermost point
# if len(intersection_points) >= 2:
#     for i in range(len(intersection_points) - 1):
#         for j in range(i + 1, len(intersection_points)):
#             point1 = intersection_points[i]
#             point2 = intersection_points[j]
#             newDistance=math.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)
#             print(f"Distance between {point1} and {point2}: {newDistance:.2f}")
#             if newDistance>distance:
#               distance = math.sqrt((point1[0] - point2[0]) ** 2 + (point1[1] - point2[1]) ** 2)


# cv2.circle(r_img_copy, tuple(lowermost_point), 5, (255, 0, 0), -1)

# print(f"Final Distance between {point1} and {point2}: {distance:.2f}")
# cv2.drawContours(r_img_copy, selected_contour, -1, (0,255,0), 2)
# cv2_imshow(r_img_copy)

